### ISSUE TITLE
Use both php and smarty view

### ISSUE THREAD

**Issue by magicbart** [NikolayMurha/SmartyModule#8]
I use Smarty as general view of my project, but i installed zfcUser.
So it does not work because zfcUser use de Php view renderer.
So can the two view system work together?

**Comment by seyfer** [comment]
:+1: 
it is very actual to have choice between phtml and tpl formats

**Comment by countless-integers** [comment]
Have you guys found that out somehow? I'm guessing it's not capable, with view helpers using the renderer being big part of the problem.
